service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_ARN:
      Ref: SNSTopic

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::bucket-task5'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::bucket-task5/*'
    - Effect: 'Allow'
      Action: 'sqs:*'
      Resource:
        - Fn::GetAtt: [SQSQueue, Arn]
    - Effect: 'Allow'
      Action: 'sns:*'
      Resource:
        Ref: SNSTopic

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-task6
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: kazucha80@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    SNSSubscriptionSpeakers:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: kazik.kluz@gmail.com
        Protocol: email
        FilterPolicy:
          is_speakers:
            - 'yes'
        TopicArn:
          Ref: SNSTopic

functions:
  importProductsFile:
    handler: handler.importProductsFile
    environment:
      S3_BUCKET: bucket-task5
    events:
      - http:
          path: import
          method: get
          authorizer:
            name: basicAuth
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:authorization-service-dev-basicAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    environment:
      S3_BUCKET: bucket-task5
    events:
      - s3:
          bucket: bucket-task5
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
